name: Build and install LLVM on Windows

on:
  # Allow running the workflow manually
  workflow_dispatch:
  # Run the workflow 4 times a year, approximately after LLVM releases
  schedule:
    - cron:  '0 6 21 FEB,MAY,AUG,NOV *'

jobs:
  build_and_test:
    name: Build LLDB-MI and run the testsuite
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Use local action install_llvm with default arguments
        uses: ./.github/actions/install_llvm
